name: Get STRATZ API token from github secret

on: 
  push:
    branches: [graphqlapi]

jobs:
  secrets-in-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Get STRATZ API token from github secret
        run: |
          echo export const STRATZ_API_TOKEN = ${{ secrets.STRATZ_API_TOKEN }} > ./config.js
        env: # Set the secret as an input
          STRATZ_API_TOKEN: ${{ secrets.STRATZ_API_TOKEN }}