name: Get STRATZ API token from github secret

on: 
  push:
    branches: [graphqlapi]

jobs:
  secrets-in-github-actions:
    runs-on: windows-latest
    steps:
      - name: Get STRATZ API token from github secret
        with: 
          STRATZ_API_TOKEN: ${{ secrets.STRATZ_API_TOKEN }}
        run: |
          STRATZ_API_TOKEN: ${{ secrets.STRATZ_API_TOKEN }}
